### ISSUE TITLE
processParameter function

### ISSUE THREAD

**Issue by cpsgu** [WedjaaOpen/ESJasperAdapter#3]
Hello, 

I think there is a bug in the function "processParamter".  In case of preparing the json object (as string) you add single comma to the string ('  in line 164 and 166 => builder.append("'"); ) 
In case of "value" has more then one character Elasticsearch  expects double comma ( " ) 

e.g  
"terms": {
   "location.raw": ['LAX', 'HOU']
}

wrong transformation: ['LAX', 'HOU']   - should be ["LAX", "HOU"]

please can you check and correct. 

best regards

**Comment by Wedjaa** [comment]
I don't touch the query, unless it's for setting the size. There is no processParameter function. Could you point out the file where this happens? Closing this one, feel free to re-open it with more details.
